[2025-01-11 04:34:12,237] AppLogger - INFO - Logger is working correctly.
[2025-01-11 04:34:12,237] AppLogger - INFO - Weather Chatbot is running...
[2025-01-11 04:34:27,238] AppLogger - INFO - Received request (raw): {'city': 'kathmandu'}
[2025-01-11 04:34:27,238] AppLogger - INFO - Received request (json dumps): {
    "city": "kathmandu"
}
[2025-01-11 04:34:27,238] AppLogger - ERROR - Error processing request: cannot access local variable 'res' where it is not associated with a value
[2025-01-11 04:34:27,239] AppLogger - ERROR - Stack trace: Traceback (most recent call last):
  File "c:\users\ganes\datascience\gen_ai\langchain\course_genai\gen_ai_in-depth\projects\weather_bot_using_googledialogflow\app.py", line 31, in get_weather
    res = json.dumps(res)
                     ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

