[2025-01-11 07:40:41,858] AppLogger - INFO - Weather Chatbot is running...
[2025-01-11 07:41:11,843] AppLogger - INFO - Received request (raw): {'city': 'california'}
[2025-01-11 07:41:11,844] AppLogger - INFO - Received request (json dumps): {
    "city": "california"
}
[2025-01-11 07:41:11,971] AppLogger - ERROR - AppException occurred: Error occurred python script name [c:\users\ganes\datascience\gen_ai\langchain\course_genai\gen_ai_in-depth\projects\weather_bot_using_googledialogflow\weather_data.py] line number [46] error message ['Weather' object has no attribute 'get_weather_data'].
