[2025-01-11 05:52:24,358] AppLogger - INFO - Weather Chatbot is running...
[2025-01-11 05:52:55,171] AppLogger - INFO - Received request (raw): {'city': 'kathmandu'}
[2025-01-11 05:52:55,172] AppLogger - INFO - Received request (json dumps): {
    "city": "kathmandu"
}
[2025-01-11 05:52:55,172] AppLogger - INFO - Created dialogflow: 
[2025-01-11 05:52:55,327] AppLogger - ERROR - AppException occurred: Error occurred python script name [c:\users\ganes\datascience\gen_ai\langchain\course_genai\gen_ai_in-depth\projects\weather_bot_using_googledialogflow\weather_data.py] line number [45] error message ['Location' object has no attribute 'sunrise_time'].
